# Tagging of metrics and verification aggregation to help filtering experiment
# sweeps
tag: float
# Global seed to make evaluation reproducible
seed: 12
# Calibration passes to be applied to the model before export
calibration_passes: 2048
# Shape of the inputs (excluding the batch dimension)
shape:
- 256
# Range of input values
range:
- -10
- 10
# Model configuration section
model:
  # Name identifying the activation function
  activation: relu
  # Test pattern for operator fusion during multi-threshold conversion
  pattern: x
  # Number of bits to use at the input
  input_bits: 8
  # Number of bits to use for the quantized activation function
  bits: 2
  # Restrict scaling type of quantizers: FP vs. POWER_OF_TWO
  restrict_scaling_type: FP
  # Restrict quantization to a narrow range or not
  narrow_range: false
  # Further (optional) arguments passed to the activation function
  activation_kwargs: {}
  # Parameters of the elementwise affine transformation inserted in front to the
  # quantized activation function
  affine:
    # Per-tensor vs. per-channel affine scale and bias
    per_channel: true
    # Range to sample the scale and bias from
    # Note: There seems to be some issue with threshold conversion if there are
    # scales close to zero, probably in relation to the RA-annotated scale?
    range:
    - 0.5
    - 8
    # Dimension to be considered as channel if per-channel
    cdim: 1
# Model to ONNX export hyperparameters
export:
  # Version of the default ONNX opset
  opset_version: 14
  # Apply the constant-folding optimization
  do_constant_folding: true
# Graph preparation configuration
prepare:
  # Enables streamlining transformations
  streamline: true
  # Enables multithreshold conversion
  thresholds: true
  # Extra scaling applied to input ranges for threshold conversion to trade off
  # conversion/rounding errors vs. conversion runtime and memory consumption
  rescale: 0.01
# FINN build configuration
build:
  # Directory to store the build outputs
  output_dir: build
  # Run synthesis to generate a .dcp for the stitched-IP output product
  stitched_ip_gen_dcp: false
  # Target clock period, i.e., inverse of target frequency
  synth_clk_period_ns: 10.0
  # Board to target with the build
  board: RFSoC2x2
  # Target shell flow: 'vivado_zynq' or 'vitis_alveo'
  shell_flow_type: vivado_zynq
  # Path to the folding configuration file
  folding_config_file: folding.yaml
  # Path to layer implementation style specialization config
  specialize_layers_config_file: specialize_layers.json
  # Force the implementation of standalone thresholds to be able to use RTL
  # implementation of the MVU
  standalone_thresholds: true
  # Maximum bit-width of quantizers converted to multi-thresholds
  max_multithreshold_bit_width: 16
  # Maximum width of MVAU stream per PE
  mvau_wwidth_max: 2048
  # FIFO nodes with depth larger than 32768 will be split
  split_large_fifos: true
  # Applies bit-width minimization: Weights and activations/accumulators
  minimize_bit_width: true
  # Enables experimental fixed-point conversion of float operations
  fixedpt_config: fixed_point.yaml
  #  # Optional: Start the build from a specific step
  #  start_step: "step_quant_activation_to_multithreshold"
#  # Optional: Stop the build after a specific step
#  stop_step: step_measure_rtlsim_performance
# Metrics aggregation configuration
metrics:
  # Path to the report file to be summarized
  # Note: remember to adjust the build directory when changing the config above
  report: build/report/post_synth_resources.json
  # Filter the report rows
  filter: (top)
  # Aggregate metrics breakdown by categories: Each category can specify a regex
  # pattern applied as a filter to the report rows, similar to the report above
  breakdown:
    # Multiply accumulate operations: Matrix-Vector and Vector-Vector
    MAC: MV|VV
    # Elementwise operations: Mul, Add, Maximum, etc.
    Elementwise: Elementwise
    # Multi-threshold operations: Activation and Quantization
    Thresholding: Thresholding
    # FIFO buffers inserted between layers
    FIFO: StreamingFIFO
    # Data-Width Converters inserted to adapt over different SIMD/PE
    DWC: DataWidthConverter
    # Sliding-Window Generators feeding convolutions
    SWG: ConvolutionInputGenerator
